import { db } from './db';
import { products } from './db/schema';

async function main() {
    const sampleProducts = [
        // Women's Collection - Silk Sarees
        {
            name: "Banarasi Silk Wedding Saree with Golden Border",
            description: "Exquisite handwoven Banarasi silk saree featuring intricate golden zari work and traditional motifs. Perfect for weddings and special occasions. Made by skilled artisans in Varanasi with pure silk threads. Dry clean only to maintain the lustrous finish.",
            price: 8500.00,
            category: "women",
            subcategory: "sarees",
            fabric: "Banarasi Silk",
            sizes: ["Free Size"],
            colors: ["Maroon", "Royal Blue", "Deep Pink"],
            images: ["banarasi_saree_1.jpg", "banarasi_saree_2.jpg", "banarasi_saree_3.jpg"],
            stockQuantity: 15,
            featured: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: "Kanchipuram Silk Festive Saree",
            description: "Traditional South Indian Kanchipuram silk saree with temple border design. Handcrafted with pure mulberry silk and gold threads. Ideal for festivals and religious ceremonies. Each saree comes with matching blouse piece.",
            price: 12000.00,
            category: "women",
            subcategory: "sarees",
            fabric: "Kanchipuram Silk",
            sizes: ["Free Size"],
            colors: ["Emerald Green", "Golden Yellow", "Royal Blue"],
            images: ["kanchi_saree_1.jpg", "kanchi_saree_2.jpg", "kanchi_saree_3.jpg"],
            stockQuantity: 8,
            featured: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: "Mysore Silk Traditional Saree",
            description: "Elegant Mysore silk saree known for its smooth texture and natural sheen. Features classic motifs and rich borders. Perfect for office wear and formal events. Made with authentic Mysore silk from Karnataka.",
            price: 5500.00,
            category: "women",
            subcategory: "sarees",
            fabric: "Mysore Silk",
            sizes: ["Free Size"],
            colors: ["Maroon", "Deep Pink", "Golden Yellow"],
            images: ["mysore_saree_1.jpg", "mysore_saree_2.jpg", "mysore_saree_3.jpg"],
            stockQuantity: 20,
            featured: false,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },

        // Women's Collection - Lehengas
        {
            name: "Designer Bridal Lehenga Choli in Royal Red",
            description: "Stunning bridal lehenga choli with heavy embroidery work and mirror details. Features a flared skirt, fitted choli, and matching dupatta. Perfect for wedding ceremonies and grand celebrations. Includes intricate threadwork and sequins.",
            price: 11500.00,
            category: "women",
            subcategory: "lehengas",
            fabric: "Net",
            sizes: ["XS", "S", "M", "L", "XL", "XXL"],
            colors: ["Red", "Pink", "Purple"],
            images: ["bridal_lehenga_1.jpg", "bridal_lehenga_2.jpg", "bridal_lehenga_3.jpg"],
            stockQuantity: 12,
            featured: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: "Festive Lehenga Set with Dupatta",
            description: "Beautiful festive lehenga set featuring georgette fabric with embellished work. Comes with matching choli and silk dupatta. Ideal for festivals, parties, and special occasions. Machine wash on gentle cycle.",
            price: 7800.00,
            category: "women",
            subcategory: "lehengas",
            fabric: "Georgette",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Blue", "Green", "Orange"],
            images: ["festive_lehenga_1.jpg", "festive_lehenga_2.jpg", "festive_lehenga_3.jpg"],
            stockQuantity: 25,
            featured: false,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: "Party Wear Velvet Lehenga",
            description: "Luxurious velvet lehenga with contemporary design and subtle embellishments. Features a modern cut with traditional appeal. Perfect for cocktail parties and evening events. Includes matching accessories.",
            price: 9200.00,
            category: "women",
            subcategory: "lehengas",
            fabric: "Velvet",
            sizes: ["XS", "S", "M", "L", "XL"],
            colors: ["Purple", "Red", "Blue"],
            images: ["party_lehenga_1.jpg", "party_lehenga_2.jpg", "party_lehenga_3.jpg"],
            stockQuantity: 18,
            featured: true,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },

        // Women's Collection - Churidars
        {
            name: "Handloom Cotton Churidar Suit with Embroidery",
            description: "Comfortable handloom cotton churidar suit featuring traditional embroidery work. Includes kurta, churidar, and dupatta. Perfect for daily wear and casual outings. Made with breathable organic cotton fabric.",
            price: 2200.00,
            category: "women",
            subcategory: "churidars",
            fabric: "Handloom Cotton",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["White", "Pink", "Blue"],
            images: ["cotton_churidar_1.jpg", "cotton_churidar_2.jpg", "cotton_churidar_3.jpg"],
            stockQuantity: 35,
            featured: false,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: "Printed Cotton Churidar Set",
            description: "Vibrant printed cotton churidar set with block print designs. Comfortable three-piece set suitable for office and casual wear. Features traditional Indian prints with modern styling. Easy care and wash-friendly.",
            price: 1650.00,
            category: "women",
            subcategory: "churidars",
            fabric: "Pure Cotton",
            sizes: ["XS", "S", "M", "L", "XL"],
            colors: ["Yellow", "Green", "Pink"],
            images: ["printed_churidar_1.jpg", "printed_churidar_2.jpg", "printed_churidar_3.jpg"],
            stockQuantity: 40,
            featured: false,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: "Embroidered Khadi Cotton Suit",
            description: "Elegant khadi cotton suit with delicate hand embroidery. Made from handspun cotton promoting traditional craftsmanship. Includes matching dupatta with mirror work. Perfect for festivals and cultural events.",
            price: 3200.00,
            category: "women",
            subcategory: "churidars",
            fabric: "Khadi Cotton",
            sizes: ["S", "M", "L", "XL"],
            colors: ["White", "Cream", "Light Blue"],
            images: ["khadi_suit_1.jpg", "khadi_suit_2.jpg", "khadi_suit_3.jpg"],
            stockQuantity: 22,
            featured: true,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },

        // Women's Collection - Salwar Suits
        {
            name: "Anarkali Suit with Jacket",
            description: "Graceful Anarkali suit in flowing silhouette with matching jacket. Features intricate thread work and sequin details. Perfect for weddings and grand celebrations. Made with premium quality fabric for comfort and elegance.",
            price: 4500.00,
            category: "women",
            subcategory: "salwars",
            fabric: "Georgette",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Pink", "Blue", "Purple"],
            images: ["anarkali_suit_1.jpg", "anarkali_suit_2.jpg", "anarkali_suit_3.jpg"],
            stockQuantity: 28,
            featured: true,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: "Punjabi Salwar Kameez Set",
            description: "Traditional Punjabi salwar kameez with authentic patiala style. Features vibrant colors and traditional motifs. Includes matching dupatta with heavy border. Ideal for festivals and cultural celebrations.",
            price: 2800.00,
            category: "women",
            subcategory: "salwars",
            fabric: "Cotton",
            sizes: ["XS", "S", "M", "L", "XL"],
            colors: ["Red", "Yellow", "Green"],
            images: ["punjabi_suit_1.jpg", "punjabi_suit_2.jpg", "punjabi_suit_3.jpg"],
            stockQuantity: 32,
            featured: false,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: "Party Wear Chiffon Salwar Suit",
            description: "Elegant chiffon salwar suit with contemporary design and embellishments. Features flowing dupatta with beaded border. Perfect for evening parties and special occasions. Dry clean recommended.",
            price: 3800.00,
            category: "women",
            subcategory: "salwars",
            fabric: "Chiffon",
            sizes: ["S", "M", "L", "XL"],
            colors: ["Black", "Navy Blue", "Maroon"],
            images: ["party_salwar_1.jpg", "party_salwar_2.jpg", "party_salwar_3.jpg"],
            stockQuantity: 16,
            featured: true,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },

        // Men's Collection - Sherwanis
        {
            name: "Traditional Wedding Sherwani for Groom",
            description: "Luxurious silk sherwani with intricate golden embroidery and royal collar design. Includes matching churidar and dupatta. Perfect for grooms and wedding ceremonies. Features hand-crafted buttons and premium lining.",
            price: 7500.00,
            category: "men",
            subcategory: "sherwanis",
            fabric: "Raw Silk",
            sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
            colors: ["Maroon", "Navy Blue", "Golden"],
            images: ["wedding_sherwani_1.jpg", "wedding_sherwani_2.jpg", "wedding_sherwani_3.jpg"],
            stockQuantity: 10,
            featured: true,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: "Festive Designer Sherwani",
            description: "Elegant designer sherwani with contemporary cuts and traditional embellishments. Made with premium silk fabric and detailed craftsmanship. Ideal for festivals, receptions, and cultural events.",
            price: 5200.00,
            category: "men",
            subcategory: "sherwanis",
            fabric: "Silk",
            sizes: ["M", "L", "XL", "XXL"],
            colors: ["Cream", "White", "Golden"],
            images: ["festive_sherwani_1.jpg", "festive_sherwani_2.jpg", "festive_sherwani_3.jpg"],
            stockQuantity: 18,
            featured: false,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: "Royal Brocade Sherwani Set",
            description: "Majestic brocade sherwani with rich texture and royal appeal. Features traditional collar and button details. Includes matching accessories for complete ethnic look. Perfect for grand celebrations and ceremonies.",
            price: 8200.00,
            category: "men",
            subcategory: "sherwanis",
            fabric: "Brocade",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Maroon", "Golden", "Navy Blue"],
            images: ["royal_sherwani_1.jpg", "royal_sherwani_2.jpg", "royal_sherwani_3.jpg"],
            stockQuantity: 12,
            featured: true,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },

        // Men's Collection - Kurtas
        {
            name: "Cotton Kurta Pajama Set",
            description: "Comfortable cotton kurta pajama set for daily wear and casual occasions. Made with breathable cotton fabric and traditional cuts. Perfect for home wear, office, and relaxed outings. Machine washable.",
            price: 1800.00,
            category: "men",
            subcategory: "kurtas",
            fabric: "Pure Cotton",
            sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
            colors: ["White", "Cream", "Light Blue"],
            images: ["cotton_kurta_1.jpg", "cotton_kurta_2.jpg", "cotton_kurta_3.jpg"],
            stockQuantity: 45,
            featured: false,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-25').toISOString(),
        },
        {
            name: "Linen Casual Kurta",
            description: "Stylish linen kurta with modern fit and comfort. Features mandarin collar and side slits. Perfect for summer wear and casual outings. Available in contemporary colors with easy care instructions.",
            price: 2200.00,
            category: "men",
            subcategory: "kurtas",
            fabric: "Linen",
            sizes: ["M", "L", "XL", "XXL"],
            colors: ["White", "Navy Blue", "Beige"],
            images: ["linen_kurta_1.jpg", "linen_kurta_2.jpg", "linen_kurta_3.jpg"],
            stockQuantity: 30,
            featured: false,
            createdAt: new Date('2024-03-30').toISOString(),
            updatedAt: new Date('2024-03-30').toISOString(),
        },
        {
            name: "Nehru Jacket with Kurta Set",
            description: "Traditional Nehru jacket paired with cotton kurta for formal ethnic look. Features button-up jacket with classic collar. Perfect for office wear, cultural events, and formal gatherings. Includes matching pajama.",
            price: 3500.00,
            category: "men",
            subcategory: "formal",
            fabric: "Cotton",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Navy Blue", "Maroon", "Black"],
            images: ["nehru_jacket_1.jpg", "nehru_jacket_2.jpg", "nehru_jacket_3.jpg"],
            stockQuantity: 20,
            featured: true,
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },

        // Kids Collection - Girls
        {
            name: "Colorful Kids Lehenga Choli in Pink",
            description: "Adorable lehenga choli set for little girls featuring colorful embroidery and comfortable fit. Made with soft cotton fabric suitable for children's sensitive skin. Perfect for festivals and family functions.",
            price: 1200.00,
            category: "kids",
            subcategory: "lehengas",
            fabric: "Cotton",
            sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
            colors: ["Pink", "Purple", "Yellow"],
            images: ["kids_lehenga_1.jpg", "kids_lehenga_2.jpg", "kids_lehenga_3.jpg"],
            stockQuantity: 25,
            featured: true,
            createdAt: new Date('2024-04-05').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: "Girls Festive Anarkali Dress",
            description: "Beautiful Anarkali dress for girls with flowy design and vibrant colors. Features comfortable elastic waist and soft fabric. Ideal for parties, festivals, and special occasions. Easy to wear and maintain.",
            price: 950.00,
            category: "kids",
            subcategory: "frocks",
            fabric: "Cotton",
            sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
            colors: ["Red", "Blue", "Green"],
            images: ["girls_anarkali_1.jpg", "girls_anarkali_2.jpg", "girls_anarkali_3.jpg"],
            stockQuantity: 35,
            featured: false,
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        {
            name: "Kids Cotton Frock with Embroidery",
            description: "Cute cotton frock with delicate embroidery work and comfortable design. Features easy-wear style perfect for active kids. Made with breathable cotton fabric in attractive colors and patterns.",
            price: 680.00,
            category: "kids",
            subcategory: "frocks",
            fabric: "Pure Cotton",
            sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
            colors: ["Pink", "Yellow", "Blue"],
            images: ["kids_frock_1.jpg", "kids_frock_2.jpg", "kids_frock_3.jpg"],
            stockQuantity: 40,
            featured: false,
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },

        // Kids Collection - Boys
        {
            name: "Boys Kurta Pajama Set",
            description: "Traditional kurta pajama set for boys in comfortable cotton fabric. Features classic cuts with modern appeal. Perfect for festivals, cultural events, and family functions. Available in child-friendly colors.",
            price: 850.00,
            category: "kids",
            subcategory: "kurtas",
            fabric: "Cotton",
            sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y", "12-13Y"],
            colors: ["White", "Cream", "Light Blue"],
            images: ["boys_kurta_1.jpg", "boys_kurta_2.jpg", "boys_kurta_3.jpg"],
            stockQuantity: 30,
            featured: false,
            createdAt: new Date('2024-04-20').toISOString(),
            updatedAt: new Date('2024-04-20').toISOString(),
        },
        {
            name: "Boys Dhoti Kurta Set",
            description: "Traditional dhoti kurta set for boys featuring authentic Indian style. Made with soft cotton fabric for comfort and ease of wearing. Perfect for cultural programs, festivals, and traditional ceremonies.",
            price: 1100.00,
            category: "kids",
            subcategory: "traditional",
            fabric: "Cotton",
            sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
            colors: ["White", "Cream", "Golden"],
            images: ["boys_dhoti_1.jpg", "boys_dhoti_2.jpg", "boys_dhoti_3.jpg"],
            stockQuantity: 20,
            featured: true,
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            name: "Boys Party Wear Kurta",
            description: "Stylish party wear kurta for boys with contemporary design and comfortable fit. Features attractive buttons and modern cuts. Perfect for parties, family gatherings, and special occasions.",
            price: 720.00,
            category: "kids",
            subcategory: "kurtas",
            fabric: "Cotton",
            sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
            colors: ["Navy Blue", "Maroon", "White"],
            images: ["boys_party_kurta_1.jpg", "boys_party_kurta_2.jpg", "boys_party_kurta_3.jpg"],
            stockQuantity: 25,
            featured: false,
            createdAt: new Date('2024-04-30').toISOString(),
            updatedAt: new Date('2024-04-30').toISOString(),
        },

        // Additional Women's Products
        {
            name: "Chanderi Silk Festive Suit",
            description: "Luxurious Chanderi silk suit with traditional handwork and elegant design. Features the famous Chanderi weave from Madhya Pradesh. Perfect for festivals and special occasions. Includes matching dupatta with golden border.",
            price: 4200.00,
            category: "women",
            subcategory: "salwars",
            fabric: "Chanderi",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Pink", "Green", "Blue"],
            images: ["chanderi_suit_1.jpg", "chanderi_suit_2.jpg", "chanderi_suit_3.jpg"],
            stockQuantity: 15,
            featured: true,
            createdAt: new Date('2024-05-05').toISOString(),
            updatedAt: new Date('2024-05-05').toISOString(),
        },
        {
            name: "Sambalpuri Cotton Saree",
            description: "Authentic Sambalpuri cotton saree with traditional ikat weave from Odisha. Features geometric patterns and vibrant colors. Perfect for cultural events and daily wear. Handwoven by skilled artisans using traditional techniques.",
            price: 2800.00,
            category: "women",
            subcategory: "sarees",
            fabric: "Sambalpuri Cotton",
            sizes: ["Free Size"],
            colors: ["Red", "Blue", "Green"],
            images: ["sambalpuri_saree_1.jpg", "sambalpuri_saree_2.jpg", "sambalpuri_saree_3.jpg"],
            stockQuantity: 18,
            featured: false,
            createdAt: new Date('2024-05-10').toISOString(),
            updatedAt: new Date('2024-05-10').toISOString(),
        },

        // Additional Men's Products
          {
            name: "Indo-Western Fusion Outfit",
            description: "Contemporary Indo-Western outfit combining traditional and modern elements. Features jacket-style kurta with fitted pants. Perfect for cocktail parties, receptions, and modern celebrations. Made with premium fabric blend.",
            price: 4800.00,
            category: "men",
            subcategory: "fusion",
            fabric: "Cotton Blend",
            sizes: ["S", "M", "L", "XL", "XXL"],
            colors: ["Black", "Navy Blue", "Charcoal"],
            images: ["indo_western_1.jpg", "indo_western_2.jpg", "indo_western_3.jpg"],
            stockQuantity: 14,
            featured: true,
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-05-15').toISOString(),
        }
    ];

      try {
        await db.insert(products).values(sampleProducts);
        console.log('✅ Indian fashion products seeder completed successfully');
    } catch (error) {
        console.error('❌ Seeder failed:', error);
    }
}

main();