import { db } from './db';
import { reviews } from './db/schema';

async function main() {
    const sampleReviews = [
        // 5-star reviews (35%)
        {
            productId: 1,
            reviewerName: 'Priya Sharma',
            rating: 5,
            comment: 'Beautiful saree! Perfect for my daughter\'s wedding. Quality is excellent. The silk feels premium and the embroidery work is stunning.',
            helpfulCount: 23,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            productId: 2,
            reviewerName: 'Meera Reddy',
            rating: 5,
            comment: 'Amazing lehenga! Got so many compliments at the wedding function. Wore it for my cousin\'s reception and felt like a princess.',
            helpfulCount: 18,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            productId: 3,
            reviewerName: 'Kavya Nair',
            rating: 5,
            comment: 'Loved the fabric quality. Fits perfectly. Great for festivals. Wore it for Diwali celebration and received countless compliments.',
            helpfulCount: 15,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            productId: 4,
            reviewerName: 'Anjali Patel',
            rating: 5,
            comment: 'Comfortable cotton kurta. Perfect for daily wear. Good value for money. The fabric is soft and breathable.',
            helpfulCount: 12,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            productId: 5,
            reviewerName: 'Divya Joshi',
            rating: 5,
            comment: 'Excellent finishing and embroidery work. Highly recommended! Perfect for Navratri celebrations.',
            helpfulCount: 20,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            productId: 8,
            reviewerName: 'Shreya Malhotra',
            rating: 5,
            comment: 'Outstanding quality churidar set. The fit is perfect and the color is exactly as shown. Worth every penny!',
            helpfulCount: 14,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            productId: 12,
            reviewerName: 'Pooja Kapoor',
            rating: 5,
            comment: 'Beautiful traditional wear. Wore it for Eid celebration and got so many compliments. Fast delivery and well packed.',
            helpfulCount: 16,
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            productId: 15,
            reviewerName: 'Neha Verma',
            rating: 5,
            comment: 'Gorgeous saree with intricate work. Perfect for special occasions. The silk quality is top-notch.',
            helpfulCount: 19,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            productId: 6,
            reviewerName: 'Rajesh Kumar',
            rating: 5,
            comment: 'Excellent sherwani for my wedding. Perfect fit and the embroidery is beautiful. Highly satisfied with the purchase.',
            helpfulCount: 22,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            productId: 9,
            reviewerName: 'Vikram Singh',
            rating: 5,
            comment: 'Great kurta for festivals. Comfortable fabric and good finishing. Wore it for Holi and it looked amazing.',
            helpfulCount: 11,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            productId: 18,
            reviewerName: 'Arjun Mehta',
            rating: 5,
            comment: 'Premium quality dhoti kurta set. Perfect for religious ceremonies. The cotton is soft and comfortable.',
            helpfulCount: 13,
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            productId: 25,
            reviewerName: 'Suresh Gupta',
            rating: 5,
            comment: 'Beautiful kids lehenga for my daughter. She looked adorable at the wedding function. Great quality and fit.',
            helpfulCount: 17,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            productId: 28,
            reviewerName: 'Amit Chandra',
            rating: 5,
            comment: 'Excellent kids kurta pajama set. Perfect for my son\'s birthday celebration. Good quality fabric and reasonable price.',
            helpfulCount: 9,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            productId: 11,
            reviewerName: 'Ravi Iyer',
            rating: 5,
            comment: 'Fantastic salwar suit. The embroidery work is exceptional. Perfect for office parties and cultural events.',
            helpfulCount: 21,
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            productId: 20,
            reviewerName: 'Rahul Agarwal',
            rating: 5,
            comment: 'Great ethnic wear collection. The nehru jacket is perfectly tailored. Impressed with the quality and delivery.',
            helpfulCount: 8,
            createdAt: new Date('2024-02-22').toISOString(),
        },

        // 4-star reviews (25%)
        {
            productId: 1,
            reviewerName: 'Kavya Nair',
            rating: 4,
            comment: 'Good quality saree but delivery was slightly delayed. Overall satisfied with the purchase. Fabric quality is nice.',
            helpfulCount: 7,
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            productId: 3,
            reviewerName: 'Anjali Patel',
            rating: 4,
            comment: 'Nice lehenga but the blouse fit is a bit tight. Had to get it altered. Otherwise, beautiful design and color.',
            helpfulCount: 10,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            productId: 7,
            reviewerName: 'Divya Joshi',
            rating: 4,
            comment: 'Good anarkali suit. The fabric is soft but the color is slightly different from the picture shown online.',
            helpfulCount: 6,
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            productId: 10,
            reviewerName: 'Meera Reddy',
            rating: 4,
            comment: 'Decent palazzo set. Comfortable for casual wear but expected better quality for the price. Good for daily use.',
            helpfulCount: 5,
            createdAt: new Date('2024-02-06').toISOString(),
        },
        {
            productId: 14,
            reviewerName: 'Priya Sharma',
            rating: 4,
            comment: 'Beautiful sharara suit but runs slightly large. Had to exchange for a smaller size. Good customer service though.',
            helpfulCount: 8,
            createdAt: new Date('2024-02-09').toISOString(),
        },
        {
            productId: 16,
            reviewerName: 'Shreya Malhotra',
            rating: 4,
            comment: 'Nice indo-western outfit. Good for parties but the material could be better. Decent value for money.',
            helpfulCount: 4,
            createdAt: new Date('2024-02-11').toISOString(),
        },
        {
            productId: 22,
            reviewerName: 'Neha Verma',
            rating: 4,
            comment: 'Good men\'s kurta but the sizing chart was not accurate. Had to return and reorder. Quality is good otherwise.',
            helpfulCount: 6,
            createdAt: new Date('2024-02-13').toISOString(),
        },
        {
            productId: 26,
            reviewerName: 'Pooja Kapoor',
            rating: 4,
            comment: 'Cute kids dress but the color faded slightly after washing. My daughter loves wearing it though.',
            helpfulCount: 7,
            createdAt: new Date('2024-02-16').toISOString(),
        },
        {
            productId: 13,
            reviewerName: 'Rajesh Kumar',
            rating: 4,
            comment: 'Good dupatta but expected heavier fabric. The print is beautiful and goes well with ethnic wear.',
            helpfulCount: 3,
            createdAt: new Date('2024-02-19').toISOString(),
        },
        {
            productId: 19,
            reviewerName: 'Vikram Singh',
            rating: 4,
            comment: 'Nice bandhgala suit but the delivery was delayed by 3 days. Quality is good and fits well after minor alterations.',
            helpfulCount: 9,
            createdAt: new Date('2024-02-21').toISOString(),
        },

        // 3-star reviews (25%)
        {
            productId: 2,
            reviewerName: 'Arjun Mehta',
            rating: 3,
            comment: 'Average quality lehenga. Fabric quality is okay but could be better for the price. Decent for one-time wear.',
            helpfulCount: 4,
            createdAt: new Date('2024-01-26').toISOString(),
        },
        {
            productId: 4,
            reviewerName: 'Suresh Gupta',
            rating: 3,
            comment: 'Nice design but color is slightly different from the picture. Fabric is decent but not premium quality.',
            helpfulCount: 5,
            createdAt: new Date('2024-01-29').toISOString(),
        },
        {
            productId: 6,
            reviewerName: 'Amit Chandra',
            rating: 3,
            comment: 'Good product but delivery was delayed by a week. Quality is decent but expected better finishing work.',
            helpfulCount: 6,
            createdAt: new Date('2024-02-04').toISOString(),
        },
        {
            productId: 8,
            reviewerName: 'Ravi Iyer',
            rating: 3,
            comment: 'Fabric quality is okay but the fit is not perfect. Had to get it altered locally. Average experience overall.',
            helpfulCount: 3,
            createdAt: new Date('2024-02-07').toISOString(),
        },
        {
            productId: 12,
            reviewerName: 'Rahul Agarwal',
            rating: 3,
            comment: 'Decent salwar suit but the dupatta quality is not good. Main suit is fine but could be better value.',
            helpfulCount: 4,
            createdAt: new Date('2024-02-14').toISOString(),
        },
        {
            productId: 17,
            reviewerName: 'Kavya Nair',
            rating: 3,
            comment: 'Average quality gown. Good for casual occasions but not suitable for formal events. Reasonable price though.',
            helpfulCount: 2,
            createdAt: new Date('2024-02-17').toISOString(),
        },
        {
            productId: 21,
            reviewerName: 'Anjali Patel',
            rating: 3,
            comment: 'The jacket is okay but expected better lining quality. Fits well but material feels cheap for the price.',
            helpfulCount: 5,
            createdAt: new Date('2024-02-23').toISOString(),
        },
        {
            productId: 24,
            reviewerName: 'Divya Joshi',
            rating: 3,
            comment: 'Kids wear quality is average. My son wore it once for a function. Okay for the price but not exceptional.',
            helpfulCount: 3,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            productId: 27,
            reviewerName: 'Meera Reddy',
            rating: 3,
            comment: 'Cute design for kids but the fabric is not very soft. My daughter complained it was itchy. Average quality.',
            helpfulCount: 6,
            createdAt: new Date('2024-02-27').toISOString(),
        },
        {
            productId: 30,
            reviewerName: 'Priya Sharma',
            rating: 3,
            comment: 'The ethnic wear is decent but nothing special. Good for casual wear but not for special occasions.',
            helpfulCount: 2,
            createdAt: new Date('2024-03-01').toISOString(),
        },

        // 2-star reviews (10%)
        {
            productId: 5,
            reviewerName: 'Shreya Malhotra',
            rating: 2,
            comment: 'Size was not as expected. Had to return the product. The size chart was misleading and caused inconvenience.',
            helpfulCount: 8,
            createdAt: new Date('2024-02-24').toISOString(),
        },
        {
            productId: 9,
            reviewerName: 'Neha Verma',
            rating: 2,
            comment: 'Color fading after first wash. Disappointed with the quality. Expected much better for this price range.',
            helpfulCount: 12,
            createdAt: new Date('2024-02-26').toISOString(),
        },
        {
            productId: 15,
            reviewerName: 'Pooja Kapoor',
            rating: 2,
            comment: 'Poor quality fabric. Not worth the money. The saree looked cheap and the border work was coming off.',
            helpfulCount: 15,
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            productId: 23,
            reviewerName: 'Rajesh Kumar',
            rating: 2,
            comment: 'The kurta material is very thin and see-through. Not suitable for formal occasions. Poor quality control.',
            helpfulCount: 9,
            createdAt: new Date('2024-03-02').toISOString(),
        },

        // 1-star reviews (5%)
        {
            productId: 11,
            reviewerName: 'Vikram Singh',
            rating: 1,
            comment: 'Worst quality product. The suit was completely different from what was shown. Stitching was poor and color was faded.',
            helpfulCount: 18,
            createdAt: new Date('2024-03-03').toISOString(),
        },
        {
            productId: 29,
            reviewerName: 'Suresh Gupta',
            rating: 1,
            comment: 'Terrible quality kids wear. The fabric was rough and my child refused to wear it. Complete waste of money.',
            helpfulCount: 14,
            createdAt: new Date('2024-03-04').toISOString(),
        },
    ];

     try {
        await db.insert(reviews).values(sampleReviews);
        console.log('✅ Reviews seeder completed successfully');
    } catch (error) {
        console.error('❌ Seeder failed:', error);
    }
}

main();